config/routes.rb
Rails.application.routes.draw do

  resources :incident_reports
  resources :groups
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :users

  root 'devices#index'
  get '/brokendevices' => 'devices#brokendevices'
  resources :devices do
    resources :loans
    resources :incident_reports
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :groups, only: [:index]
      resources :devices, only: [:index, :show, :create] do
        resources :loans, only: [:create, :update, :destroy]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "users/registrations",
                                        :sessions => "users/sessions"
                                      }

end

app/models/incident_report.rb
# == Schema Information
#
# Table name: incident_reports
#
#  id          :integer          not null, primary key
#  description :text
#  usable     :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  device_id   :integer
#

class IncidentReport < ApplicationRecord
  validates_presence_of :description
	belongs_to :device
  belongs_to :user

  #before_create :set_active_incident_report

  def self.usable
    where(usable: true)
  end

  def set_active_incident_report
    self.usable = true
  end

  def name
    try(:user).try(:name) || "No Name"
  end
end

app/controllers/incident_reports_controller.rb
class IncidentReportsController < ApplicationController
  before_action :set_device
  before_action :set_incident_report, only: [:show, :edit, :update, :destroy]

  # GET /incident_reports
  # GET /incident_reports.json
  def index
    #@incident_reports = IncidentReport.all
    @incident_reports = @device.incident_reports

  end

  # GET /incident_reports/1
  # GET /incident_reports/1.json
  def show
  end

  # GET /incident_reports/new
  def new
    @incident_report = IncidentReport.new(:device_id => params[:device_id])
  end

  # GET /incident_reports/1/edit
  def edit
  end

  # POST /incident_reports
  # POST /incident_reports.json
  def create
    #@incident_report = IncidentReport.new(incident_report_params)
    @incident_report = @device.incident_reports.build(incident_report_params)

    respond_to do |format|
      if @incident_report.save
        format.html { redirect_to device_incident_reports_url, notice: 'Incident report was successfully created.' }
        format.json { render :show, status: :created, location: @incident_report }
      else
        format.html { render :new }
        format.json { render json: @incident_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incident_reports/1
  # PATCH/PUT /incident_reports/1.json
  def update
    respond_to do |format|
      if @incident_report.update(incident_report_params)
        format.html { redirect_to device_incident_reports_url, notice: 'Incident report was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident_report }
      else
        format.html { render :edit }
        format.json { render json: @incident_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_reports/1
  # DELETE /incident_reports/1.json
  def destroy
    @incident_report.update(usable: true)
    respond_to do |format|
      format.html { redirect_to device_incident_reports_url, notice: 'Device is now usable' }
      format.json { head :no_content  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident_report
      @incident_report = IncidentReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_report_params
      params.require(:incident_report).permit(:description, :usable, :device_id, :user_id)
    end

    def set_device
      @device = Device.find(params[:device_id])
    end
end

app/helpers/incident_reports_helper.rb
module IncidentReportsHelper
end

app/views/incident_reports/_form.html.erb
<%= form_for([@device, @incident_report]) do |f| %>
  <% if incident_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incident_report.errors.count, "error") %> prohibited this incident_report from being saved:</h2>

      <ul>
      <% incident_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center">
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, :style => "text-align: center", :placeholder => "Please describe what happened to the device" %>
      </br>
    </div>


    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="field">
      <%= f.check_box :usable, checked: true %>
      <%= f.label :usable, for: "incident_report_usable" %>
    </div></br>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div></br>
<% end %>

app/views/incident_reports/edit.html.erb
<h1>Editing Incident Report</h1>

<%= render 'form', incident_report: @incident_report %>

<%= link_to 'Show', @incident_report %> |
<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center", class="card-panel  light-blue lighten-3">Incident Reports</h1>

<table class="highlight centered bordered card-panel  light-blue lighten-5">
  <thead>
    <tr>
      <th>Loanee</th>
      <th>Description</th>
      <th>usable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incident_reports.reverse.each do |incident_report| %>
      <tr>
        <td><%= incident_report.name %></td>
        <td><%= incident_report.description %></td>
        <td><%= incident_report.usable %></td>
        <% if incident_report.usable == false %>
        <td><%= link_to 'Device fixed/replaced?', [@device, incident_report], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div align="center">
  <%= link_to 'Back to Devices', devices_path %>
</div>

app/views/incident_reports/new.html.erb
<h1 align="center">New Incident Report</h1>

<%= render 'form', incident_report: @incident_report %>

<div align="center">
	<%= link_to 'Incident Report History', device_incident_reports_path %> |
	<%= link_to 'Back to Devices', devices_path %>
</div>

app/views/incident_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @incident_report.description %>
</p>

<p>
  <strong>usable:</strong>
  <%= @incident_report.usable %>
</p>

<%= link_to 'Edit', edit_incident_report_path(@incident_report) %> |
<%= link_to 'Back', incident_reports_path %>