config/routes.rb
Rails.application.routes.draw do

  resources :incident_reports
  resources :groups
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :users

  root 'devices#index'
  get '/brokendevices' => 'devices#brokendevices'
  resources :devices do
    resources :loans
    resources :incident_reports
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :groups, only: [:index]
      resources :devices, only: [:index, :show, :create] do
        resources :loans, only: [:create, :update, :destroy]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "users/registrations",
                                        :sessions => "users/sessions"
                                      }

end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  group_name :string
#  group_id   :integer
#  assigned   :boolean
#

class Device < ApplicationRecord

	validates_presence_of :name, :group_id

	belongs_to :group

	has_many :incident_reports, ->() { order(created_at: :asc)}

	has_many :loans, ->() { order(created_at: :desc)}

	has_one :active_loan, ->() { where(active: true) }, class_name: Loan

	has_one :active_incident_report, ->() { where(usable: false) }, class_name: IncidentReport

  has_many :users, through: :loans

  #scopes are ways to shorten commonly used queries.
	scope :broken, ->{joins(:incident_reports).where(incident_reports: {usable: false})}
	#scope :not_broken, ->{joins(:incident_reports).where.not(incident_reports: {usable: false}).uniq}
	scope :not_broken, ->{all.includes(:loans, :incident_reports).map { |device| device if device.incident_reports.empty? || device.incident_reports.last[:usable] }.compact}

	def loan_name
		active_loan.name
	end

	def device_group
		try(:group).try(:name) || "No Group"
	end

  def working_device_name
    incident_reports.empty? || with_incident_report_and_usable? ? name : nil
  end

  def broken_device_name
  	active_incident_report.present? ? name : nil
  end

  def loanee_name
  	active_loan.present? ? active_loan.user.name : nil
  end

  def loan_id
  	active_loan.present? ? active_loan.id : nil
  end


	# def is_usable?
	# 	true if (self.incident_reports.count != 0) && self.incident_reports.last[:usable]
	# end

	# def one_active_incident_report
	# 	if self.active_incident_reports(:reload).count >= 1
 #      errors.add(:base, "Exceeded thing limit")
 #    end
 #  end
private

  def with_incident_report_and_usable?
    (incident_reports.count > 0) && incident_reports.last[:usable]
  end

end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < ApplicationController
  respond_to :json
  skip_before_action :authenticate_user!

  def index
    respond_with Device.not_broken.as_json(only: [:id, :name], include: {group: {only: :name}})
  end

  def show
    respond_with Device.find(params[:id])
  end

  def create
    device = Device.new(device_params)
    if device.save
      render json: device, status: 201, location: [:api, device]
    else
      render json: { errors: device.errors }, status: 422
    end
  end

  private

    def device_params
      params.require(:device).permit(:name, :group_id)
    end
end

app/controllers/devices_controller.rb
require 'rqrcode'
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]


  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.not_broken
  end

  def brokendevices
    @devices = Device.broken
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @qr = RQRCode::QRCode.new( '#{@device.id}', :size => 4, :level => :h )
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    respond_to do |format|
      if @device.save
        format.html { redirect_to devices_path, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :id_number, :group_id, :user_ids)
    end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div align="center">
      <i class="material-icons large">stay_primary_portrait</i>
    </div>
    <div align="center" class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :style => "text-align: center", :placeholder => "Please enter a valid Device name"  %>
    </div>

    <%= f.hidden_field :device_id, value: device.id %>

    <div align="center" class="field">
      <%= f.label :Group %>
      <%= f.collection_select(:group_id, Group.all, :id, :name, {}, class: "browser-default") %></br>
    </div>


    <div align="center" class="actions spacer10">
      <%= f.submit %></br>
    </div>
  </div>
<% end %>

app/views/devices/brokendevices.html.erb
<h2 align="center", class="z-depth-5">
Broken Devices
</h2>
<div class="container">
  <% @devices.group_by(&:device_group).each do |group_name, devices| %>

    <h3 align="center", class="light-blue lighten-3"> <%= group_name %> </h3>

    <table class="highlight centered bordered card-panel  light-blue lighten-5">
      <thead>
        <tr>
        <th class=>Device Name</th>
        <th>Loanee</th>
        <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% devices.each do |device| %>
          <tr/>
            <td><%= device.name %></td>
            <% if device.active_loan.present? %>
              <td><%= device.loan_name %></td>
            <% elsif device.active_incident_report.present?  %>
              <td>Device Unavailable</td>
            <% else %>
              <td><%= link_to 'Loan-IT', new_device_loan_path(device) %></td>
            <% end %>
            <td><%= %></td>
            <td><%= link_to 'Show loan history', device_loans_path(device) %></td>
            <td><%= link_to 'Edit Device', edit_device_path(device) %></td>
            <% if device.active_incident_report.present? %>
              <td><%= link_to "Broken - View Report", device_incident_reports_url(device) %></td>
            <% else %>
              <td><%= link_to 'Create Incident Report', new_device_incident_report_path(device) %></td>
            <% end %>
            <% if device.active_loan.present? %>
              <td><%= link_to 'Relinquish Device', device_loan_path(device, device.active_loan), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% end %>
</div>




<br>

<div align="center">
  <%= link_to 'Back to devices', devices_path %>
</div>

app/views/devices/edit.html.erb
<h1 align="center">Editing Device</h1>

<%= render 'form', device: @device %>
<div align="center">
	<%= link_to 'Show', @device %> |
  <%= link_to 'Back', devices_path %>
</div>

app/views/devices/index.html.erb
<h2 align="center", class="z-depth-5">
<span class="black-text"><%= Time.now.strftime("%H:%M     -    %A    -    %d/%m/%Y") %></span>
</h2>
<div class="container">
  <% @devices.group_by(&:device_group).each do |group_name, devices| %>

    <h3 align="center", class="card-panel light-blue lighten-2"><span class="black-text"> <%= group_name %></span> </h3>

    <table class="highlight centered bordered card-panel light-blue lighten-4">
      <thead>
        <tr>
        <th><i class="material-icons">stay_primary_portrait</i></th>
        <th><i class="material-icons">account_circle</i></th>
        <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% devices.each do |device| %>
          <tr/>
            <td><%= device.name %></td>
            <% if device.active_loan.present? %>
              <td><%= device.loan_name %></td>
            <% else %>
              <td><%= link_to 'Loan-IT', new_device_loan_path(device) %></td>
            <% end %>
            <td><%= %></td>
            <td><%= link_to 'Show loan history', device_loans_path(device) %></td>
            <td><%= link_to 'Edit Device', edit_device_path(device) %></td>
            <% if device.active_loan.present? %>
              <td><%= link_to 'Relinquish Device', device_loan_path(device, device.active_loan), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% end %>
</div>




<br>

app/views/devices/new.html.erb
<h1 align="center">New Device</h1>

<%= render 'form', device: @device %>

<div align="center" class="spacer100">
	<%= link_to 'Back', devices_path %>
</div>

app/views/devices/show.html.erb
<div align="center">
  <h2>
  	<strong>Name:</strong>
 	  <%= @device.name %>
  </h2>
</p>
<div class="container centered">
<%= raw @qr.as_html%> </br>
</div>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>