config/routes.rb
Rails.application.routes.draw do

  resources :incident_reports
  resources :groups
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :users

  root 'devices#index'
  get '/brokendevices' => 'devices#brokendevices'
  resources :devices do
    resources :loans
    resources :incident_reports
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :groups, only: [:index]
      resources :devices, only: [:index, :show, :create] do
        resources :loans, only: [:create, :update, :destroy]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "users/registrations",
                                        :sessions => "users/sessions"
                                      }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  group_id               :integer
#  admin                  :boolean          default(FALSE)
#  name                   :string
#  image                  :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Authenticable

  mount_uploader :image, ImageUploader
  validates :auth_token, uniqueness: true
  before_create :generate_authentication_token!

  has_many :loans, ->() { where(active: true).order(created_at: :desc) }

  has_many :incident_reports

  has_many :devices, through: :loans

  has_many :groups

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user_email
  	try(:email)
	end

	def device_names
    devices.collect(&:name)
  end

  def password_required?
    self.admin
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	respond_to :json
  skip_before_action :authenticate_user!

  def index
    respond_with User.all.as_json(only: [:id, :name, :email])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  respond_to :json

  def create
    build_resource(sign_up_params)
     resource.save
     yield resource if block_given?
     if resource.persisted?
       if resource.active_for_authentication?
         set_flash_message! :notice, :signed_up
         sign_up(resource_name, resource)
         render :json => resource.as_json(:auth_token=>resource.auth_token, :email=>resource.email), :status=>201
       else
         warden.custom_failure!
         render :json => resource.errors, :status=>422
       end
     else
       warden.custom_failure!
       render :json => resource.errors, :status=>422
     end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
     u.permit(:email, :password, :password_confirmation, :name, :admin)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
     u.permit(:email, :password, :password_confirmation, :name, :admin)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json, :html

  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user, store: false
      user.generate_authentication_token!
      user.save
      render json: {auth_token: user.auth_token, success: true, email: user.email, user_id: user.id, user_name: user.name}, status: 200
    else
      render json: { errors: "Invalid email or password" }, status: 422
    end
  end

  def destroy
    user = User.find_by(auth_token: params[:id])
    user.generate_authentication_token!
    user.save
    head 204
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      #if params[:user][:password].blank?
			 #  params[:user].delete(:password)
			 #  params[:user].delete(:password_confirmation)
		  # end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin, :name, :image, :remove_image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center">
    <i class="material-icons medium">account_circle</i>
  </div>
  <div align="center">
    <%= f.label :name %>
    <%= f.text_field :name, :style => "text-align: center", :placeholder => "Please enter your full name" %>
  </div>


  <div align="center">
    <i class="material-icons medium">email</i>
  </div>
  <div align="center">
    <%= f.label :email %><br />
    <%= f.email_field :email, :style => "text-align: center", :placeholder => "Please enter a valid email"  %>
  </div></br>

  <div align="center">
    <i class="material-icons medium">vpn_key</i>
  </div>
  <div align="center">
    <%= f.label :password, "New password" %><br />
    <%= f.password_field :password, :style => "text-align: center", :placeholder => "Admins require a password, regular user's do not" %>
  </div></br>

  <div align="center">
    <i class="material-icons medium">replay</i>
  </div>
  <div align="center"><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, :style => "text-align: center"%></div>

  <div align="center">
    <i class="material-icons medium">add_a_photo</i>
  </div>
  <div align="center" class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %></br>
    <% if f.object.image? %>
      <%= image_tag f.object.image.url %>
      <%= f.check_box :remove_image %>
      <%= f.label :remove_image, for: "user_remove_image" %>
    <% end %>
  </div></br>

  <div align="center" class="field">
    <%= f.check_box (:admin) %>
    <%= f.label :admin, for: "user_admin" %></br>
  </div></br>

  <div align="center" class="actions">
    <%= f.submit %></br>
  </div></br>
<% end %>

app/views/users/_passwords.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :password, "New password" %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <div class="actions">
    <%= f.submit "Change password" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 align="center">Edit user</h2>

<%= render 'form' %>
<p></p>
<div align="center">
	<%= link_to 'All users', users_path %>
</div>

app/views/users/index.html.erb
 <h1 align="center", class="z-depth-5">All Users</h1>
<% @users.group_by(&:user_email).each do |email, users| %>


	<h3 align="center", class="card-panel  light-blue lighten-2"> <%= email %> </h3>

	<% users.each do |user| %>
   	<h5 align="center", class="card-panel  light-blue lighten-4"><%= user.name %> </h5>
   	<div align="center">
		  <%= link_to "Edit", edit_user_path(user) %> |
		  <%= link_to "Show", user_path(user) %>
	  </div>
	  <div> </div>
		<table class="highlight centered bordered card-panel light-blue lighten-5 spacer10">
			<thead>
				<tr>
				<% if user.devices.present? %>
				<th>Device Name</th>
				<th colspan="3"></th>
				<% else %>
				<th> No Device Loaned</th>
				<% end %>
				</tr>
			</thead>

			<tbody>
				<% user.devices.each do |device| %>
					<tr>
						<td> <%= device.name %> </td>
					  <td><%= link_to "Edit", edit_device_path(device) %></td>
					  <td><%= link_to "Show Loan History", device_loans_path(device) %></td>
					</tr>
				<% end %>
			</tbody>
	  </table>
	  <div class="divider"></div>
	<% end %>
<% end %>
<div align="center">
	<%= link_to "New User", new_user_path %> |

	<%= link_to 'Back to Devices', devices_path %>
</div>

app/views/users/new.html.erb
<h2 align="center">Sign up</h2>

<%= render 'form' %>
<div align="center">
	<%= link_to 'All users', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p align="center">
  <strong>Email:</strong>
  <h3 align="center"><%= @user.email %></h3>
</p>
<p align="center">
  <strong>Name:</strong>
  <h3 align="center"><%= @user.name %></h3>
</p>
<% unless @user.image.blank? %>
	<p>
	  <strong>Image:</strong>
	  <%= image_tag @user.image.thumb.url %>
	</p>
<% end %>

<div align="center">
	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>
</div>