config/routes.rb
Rails.application.routes.draw do

  resources :incident_reports
  resources :groups
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :users

  root 'devices#index'
  get '/brokendevices' => 'devices#brokendevices'
  resources :devices do
    resources :loans
    resources :incident_reports
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :groups, only: [:index]
      resources :devices, only: [:index, :show, :create] do
        resources :loans, only: [:create, :update, :destroy]
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "users/registrations",
                                        :sessions => "users/sessions"
                                      }

end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id         :integer          not null, primary key
#  signature  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  device_id  :integer
#  user_id    :integer
#  active     :boolean          default(FALSE)
#

class Loan < ApplicationRecord

  validates_presence_of :user_id
  belongs_to :device
  belongs_to :user

  before_create :set_active_loan

  mount_uploader :signature, SignatureUploader

  def self.active
    where(active: true)
  end

  def set_active_loan
    self.active = true
  end

  def name
    try(:user).try(:name) || "No Name"
  end

end

app/controllers/api/v1/loans_controller.rb
class Api::V1::LoansController < ApplicationController
  respond_to :json
  skip_before_action :authenticate_user!
  before_action :set_device
  before_action :set_loan, only: [:update, :destroy]

  def create
    loan = @device.loans.build(loan_params)
    if loan.save
      render json: loan, status: 201, location: [:api, @device, loan]
    else
      render json: { errors: loan.errors }, status: 422
    end
  end

  def update
    if @loan.update(loan_params)
      render json: @loan, status: 201, location: [:api, @device, @loan]
    else
      render json: { errors: @loan.errors }, status: 422
    end
  end

  def destroy
	  @loan.update(active: false)
  end

  private

    def loan_params
      params.require(:loan).permit(:signature, :user_id)
    end

    def set_device
      @device = Device.find(params[:device_id])
    end

    def set_loan
      @loan = Loan.find(params[:id])
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_device
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = @device.loans
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new(:device_id => params[:device_id])
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    #@loan = Loan.new(loan_params)
    @loan = @device.loans.build(loan_params)

    # instructions = JSON.parse(params[:output]).map { |h| "line #{h['mx'].to_i},#{h['my'].to_i} #{h['lx'].to_i},#{h['ly'].to_i}" } * ' '
    # tempfile = Tempfile.new(["signature", '.png'])
    # Open3.popen3("convert -size 600x100 xc:transparent -stroke blue -draw @- #{tempfile.path}") do |input, output, error|
    #   input.puts instructions
    # end
    # @yourmodel.signature = tempfile

    respond_to do |format|
      if @loan.save
        format.html { redirect_to device_loans_url, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to device_loans_url, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.update(active: false)
    respond_to do |format|
      format.html { redirect_to device_loans_url, notice: 'Device was relinquished.' }
      format.json { head :no_content  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:signature, :user_id)
    end

    def set_device
      @device = Device.find(params[:device_id])
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= simple_form_for([@device, @loan]) do |f| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h5>
    <div class="field">
      <%= f.collection_select(:user_id, User.all, :id, :name, {prompt: 'Select Loanee'}, class: "browser-default") %>
    </div>
  </h5>

  <%= f.input_field :signature, as: :hidden, class: 'signature_pad_input' %>
  <div class="signature_pad text-center">
    <div class="signature_pad_body">
      <canvas></canvas>
    </div>
    <div class="signature_pad_footer">
      <div class="text-muted">Sign above</div>
      <button type="button" class="btn btn-default signature_pad_clear">Clear</button>
      <%= f.button :submit, 'Save', class: 'btn btn-success signature_pad_save'  %>
    </div>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', device_loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Loans</h1>
<h6 align="right"><%= link_to 'QR Code', device_url(@device) %></h6>
<h2 align="center", class="card-panel  light-blue lighten-3"><%= @device.name %></h2>
<div class="row">
  <div class="col s6"><h5 align="center"><%= link_to 'Create Incident Report', new_device_incident_report_path(@device) %></h5></div>
  <div class="col s6"><h5 align="center"><%= link_to 'Incident Report History', device_incident_reports_path(@device) %></h5></div>
</div>




<table class="highlight centered bordered card-panel  light-blue lighten-5">
  <thead>
    <tr>
      <th>Signature</th>
      <th>Time</th>
      <th>Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.signature %></td>
        <td><%= loan.created_at %></td>
        <td><%= loan.name  %></td>

        <% if loan.active %>
        <td><%= link_to 'Relinquish Device', [@device, loan], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <% end %>

      </tr>
      </tr>
    <% end %>
  </tbody>
</table>




<br>
<div align="center">
  <h5><%= link_to 'Back to devices', devices_path %></h5>
</div>

app/views/loans/new.html.erb
<h1 align="center", class="card-panel light-blue lighten-3"><%= "New Loan for #{@device.name}" %></h1>

<%= render 'form', loan: @loan %>
<div align="center">
	<%= link_to 'Back', devices_path %>
</div>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Signature:</strong>
  <%= image_tag @loan.signature.thumb.url %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', device_loans_path %>